version: '3.8'

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: webstream_db
    environment:
      POSTGRES_DB: webstream
      POSTGRES_USER: webstream
      POSTGRES_PASSWORD: webstream_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - webstream_network

  # Бэкенд API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webstream_backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://webstream:webstream_password@postgres:5432/webstream?sslmode=disable
      JWT_SECRET: your_jwt_secret_key_here_change_in_production
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - webstream_network
    privileged: true
    cap_add:
      - SYS_ADMIN

  # Фронтенд Vue 3
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webstream_frontend
    environment:
      VITE_API_URL: http://localhost:3000/api
      VITE_WS_URL: ws://localhost:3000
      VITE_APP_TITLE: WebStream
      VITE_APP_VERSION: 1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - webstream_network

  # Nginx с RTMP модулем для стриминга
  nginx:
    image: tiangolo/nginx-rtmp
    container_name: webstream_nginx
    ports:
      - "1935:1935"  # RTMP порт для OBS
      - "8083:80"    # HTTP порт для HLS (изменен с 8082 на 8083)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/rtmp.conf:/etc/nginx/rtmp.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./streams:/var/www/streams  # HLS файлы
    depends_on:
      - frontend
      - backend
    networks:
      - webstream_network

volumes:
  postgres_data:

networks:
  webstream_network:
    driver: bridge
    internal: false  # Разрешаем внешние соединения
    ipam:
      config:
        - subnet: 172.25.0.0/16  # Используем отдельную подсеть, не конфликтующую с base
